### ISSUE TITLE
oakvar.exceptions.BadFormatError: error: All samples have the reference genotype.

### ISSUE THREAD

**Issue by antonkulaga** [rkimoakbioinformatics/oakvar#10]
I deployed latest version of oakvar on my server ( http://agingkills.eu:8080 ), when I upload there my own genome ( https://drive.google.com/file/d/1hrbtUbeerTV6oj7Kfdhee-Ba7Wb4ue1m/view?usp=sharing  ), I get the following errors http://agingkills.eu:8080/submit/jobs/220731-230442/log
```
2022/07/31 23:05:01 oakvar.converter     started: Sun Jul 31 23:05:01 2022
2022/07/31 23:05:01 oakvar.converter     Input file(s): /home/antonkulaga/.oakvar/jobs/default/220731-230442/antonkulaga.vcf
2022/07/31 23:05:07 oakvar.converter     input format: vcf
2022/07/31 23:05:08 oakvar.converter     Traceback (most recent call last):
  File "/data/users/antonkulaga/micromamba/envs/dna-seq/lib/python3.9/site-packages/oakvar/base/converter.py", line 26, in convert_file
    yield ln, line, self.convert_line(line)
  File "/home/antonkulaga/.oakvar/modules/converters/vcf-converter/vcf-converter.py", line 216, in convert_line
    raise BadFormatError('All samples have the reference genotype.')
oakvar.exceptions.BadFormatError: error: All samples have the reference genotype.
```

**Comment by rkimoakbioinformatics** [comment]
That message just means that there was a variant which did not exist in any sample. `.err` file will show exactly which variants were like that. Still, seeing the message in `.log` as an error can be alarming. I'll look into a solution for that.

**Comment by rkimoakbioinformatics** [comment]
@antonkulaga oakvar v2.5.9 has been released with a fix. `vcf-converter` v2.1.5 is also needed. Below are the steps to get the fix.

```
pip install -U oakvar
ov store fetch
ov module install vcf-converter
```

By the way, `ov store fetch` updates the local store cache, like `apt update`. If there is nothing new, it'll show a message and exit and thus doesn't waste time. In the future, `ov module install` will automatically perform the fetch.

The `.log` file will not show the error and the `.err` file will show the file name, line number, and the error message.

**Comment by antonkulaga** [comment]
After update ov guide des not run at all. It shows regular
```
OakVar Server is served at 0.0.0.0:8080
(To quit: Press Ctrl-C or Ctrl-Break if run on a Terminal or Windows, or click "Cancel" and then "Quit" if run through OakVar app on Mac OS)
```
But then crashes without any messages.
Logs do not show anything, while gui status json shows  "status": "Error".

I really appreciate how fast you react to issues. But maybe you should consider setting up continius integration (i.e. Travis or something) because each minor update can crash everything.

Also, what are the instructions of clean reinstall without effecting downloaded modules? I have around 60GB modules downloaded, do not want to accidentally erase them and download again.

**Comment by rkimoakbioinformatics** [comment]
@antonkulaga I do have automatic test which is checked with before each release. However, I don't have automatic test of GUI yet and I believe CircleCI as such does not test GUI either. I'm all for automatic testing, so please let me know if you know any good one for testing GUI.

Regarding the issue, probably something went wrong while loading the status of the job which erred. Can you show me the content of the status.json file you mentioned?

For clean reinstallation, `ov system setup --clean` will do. `ov system setup` command never erases the modules folder. What's erased by `--clean` is the configuration files and the store cache. If you want to save even more time, you can delete `store.sqlite` and `system.yml` file from the directory of `conf_dir` shown by `ov system config` and run `ov system setup`.

**Comment by rkimoakbioinformatics** [comment]
By the way, I have just released oakvar v2.5.10 which some fixes. Please use this version.

**Comment by antonkulaga** [comment]
Update did not help.
![Screenshot from 2022-08-01 14-59-19](https://user-images.githubusercontent.com/842436/182143181-54ddb9d3-67a4-4365-8a1a-852d01116c99.png)
```
{
  "annotators": [],
  "assembly": "hg38",
  "db_path": "/data/users/antonkulaga/gui.sqlite",
  "id": "antonkulaga",
  "job_dir": "/data/users/antonkulaga",
  "note": "",
  "open_cravat_version": "2.5.5",
  "orig_input_fname": [
    "gui"
  ],
  "orig_input_path": [
    "/data/users/antonkulaga/gui"
  ],
  "reports": [],
  "run_name": "gui",
  "status": "Error",
  "submission_time": "2022-07-31T01:48:34.083586",
  "viewable": false
}
```
log and err are empty.

Regarding Cricle CI, for gui testing you have to run headless chrome.

**Comment by rkimoakbioinformatics** [comment]
@antonkulaga Even with that status.json file replacing the same file of a job, `ov gui` still runs fine in my system. Does anything show with `ov gui --debug`?

Another reason may be related to `ov gui` and your custom module, since that would be the main difference between your and my system. Maybe something happened while the gui loaded the module's information. Can you share with me the yml file content of your custom module?

**Comment by antonkulaga** [comment]
Debug flag was useful, here is the info:
```
Traceback (most recent call last):
  File "/data/users/antonkulaga/micromamba/envs/dna-seq/lib/python3.9/site-packages/oakvar/cli/gui.py", line 431, in server_done
    task.result()
  File "/data/users/antonkulaga/micromamba/envs/dna-seq/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/data/users/antonkulaga/micromamba/envs/dna-seq/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/data/users/antonkulaga/micromamba/envs/dna-seq/lib/python3.9/site-packages/oakvar/cli/gui.py", line 459, in start
    self.setup_routes()
  File "/data/users/antonkulaga/micromamba/envs/dna-seq/lib/python3.9/site-packages/oakvar/cli/gui.py", line 540, in setup_routes
    self.setup_webapp_routes()
  File "/data/users/antonkulaga/micromamba/envs/dna-seq/lib/python3.9/site-packages/oakvar/cli/gui.py", line 502, in setup_webapp_routes
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/antonkulaga/.oakvar/modules/webapps/variantreport/route.py", line 12, in <module>
    from cravat import ConfigLoader
ImportError: cannot import name 'ConfigLoader' from 'cravat' (/data/users/antonkulaga/micromamba/envs/dna-seq/lib/python3.9/site-packages/cravat/__init__.py)
```
So, an obvios error from one of the modules. I am curios why I had no info in err and log files from regular gui then? If such thing is displayed in debug mode it should at least go to logs in regular one

**Comment by rkimoakbioinformatics** [comment]
Ok. Two things. One is `variantreport` module itself. I'll fix that one and publish a new version.

Regarding the log, `ov gui`'s log is `wcravat.log` file in `conf_dir` shown by `ov system config`. Does it have the error messages?

**Comment by antonkulaga** [comment]
Yes, it does, but when I run gui it creates:
```
gui.err  gui.log  gui.status.json
```
So I expected all gui-related logs be there and did not think about searching in:
```
.oakvar/logs/wcravat.log
```
Maybe you can clarify this for users in the docs, because it is contrintuitive.

**Comment by antonkulaga** [comment]
Afteer deleteting the module things got fine. So I close this issue

**Comment by rkimoakbioinformatics** [comment]
@antonkulaga Ok great. Regarding `gui.err`, `gui.log`, and `gui.status.json`, those three types of files are typically created by `ov run`. `ov gui` does not create those files. A possible scenario is, if you ran `ov run gui`, then those files would be created in your working directory. Please let me know if those files keep being generated with `ov gui`, since that would be a bug.
