### ISSUE TITLE
'list' object has no attribute 'rstrip' in multiple modules

### ISSUE THREAD

**Issue by antonkulaga** [rkimoakbioinformatics/oakvar#11]
After running annotations on my own genome (log is http://pic:8080/submit/jobs/220731-230442/log ) I noticed that many modules have
```
'list' object has no attribute 'rstrip'
```
mistake. They all reference File "/data/users/antonkulaga/micromamba/envs/dna-seq/lib/python3.9/site-packages/oakvar/base/annotator.py", line 322, in run so it is not clear for me wether it is bug in modules or in oakvar itself.

**Comment by rkimoakbioinformatics** [comment]
@antonkulaga Thanks. I'll take a look.

**Comment by rkimoakbioinformatics** [comment]
@antonkulaga Which modules had the error message (just one would be good)? Also, what was the full stack trace, as I don't see rstrip in line 322.

**Comment by antonkulaga** [comment]
Ah, sorry, I accidentally gave a link to the web log you cannot open. I enclose the file
[log.txt](https://github.com/rkimoakbioinformatics/oakvar/files/9234357/log.txt)
As you see oakvar.polyphen2 and oakvar.litvar have such issue.
The input file is my genome https://drive.google.com/file/d/1hrbtUbeerTV6oj7Kfdhee-Ba7Wb4ue1m/view?usp=sharing

**Comment by rkimoakbioinformatics** [comment]
@antonkulaga no worries. Two things were happening. One is the modules' own problem. What your genome as an input exposed edge cases which led to errors. Secondly, the error from `annotator.py` itself. However, the line which gave the error about rstrip was actually removed today for better error output, so if you install the newest version of oakvar, the second problem should go away.

I'll publish the fixed modules for OakVar and let you know.

**Comment by rkimoakbioinformatics** [comment]
@antonkulaga Problem modules in your log file were
```
pharmgkb
polyphen2
dida
dbsnp
litvar
```
It seems that some module(s) have problem in their data which caused the error in your job, which came from previous versions. I'm fixing those and will release newer versions for OakVar. I'll let you know as they are released. Fixed versions of `gencode` and `pharmgkb` have already been released. `polyphen2` is being fixed now.

**Comment by antonkulaga** [comment]
By the way, oakvar modules are in https://github.com/KarchinLab/open-cravat-modules-karchinlab or you made a separate repo for them?

**Comment by rkimoakbioinformatics** [comment]
@antonkulaga OakVar modules are made from a separate repo.

**Comment by antonkulaga** [comment]
Do original plugin maintainers commit there as well? For example, we made feature request to clinvar and there were some commits from plugin maintainers https://github.com/KarchinLab/open-cravat-modules-karchinlab/issues/12 They did not publish it on opencravat server but it looks like the plugin was updated in terms of code.

**Comment by rkimoakbioinformatics** [comment]
@antonkulaga I believe so.

**Comment by antonkulaga** [comment]
@rkimoakbioinformatics so far looks like it is running the old clinvar.
From which repository does oakvar takes Clinvar module, can you give me a link to check?

**Comment by rkimoakbioinformatics** [comment]
@antonkulaga I believe that OakVar points to the latest version as well as OpenCRAVAT does. `ov module install clinvar` (or `ov module update clinvar`) will install the latest version.

**Comment by antonkulaga** [comment]
I do not see it anymore, probably I can close this
