### ISSUE TITLE
improvement of UI loading speed (minor issue)

### ISSUE THREAD

**Issue by antonkulaga** [rkimoakbioinformatics/oakvar#14]
I get 15-20 seconds of rotating black wheels when I open oakvar. It is a minor UI issue but a bit annoying.

**Comment by rkimoakbioinformatics** [comment]
I agree. I'll look into speeding it up. I am actually planning to overhaul the GUI, so this issue may become irrelevant soon. Either this or a quick fix will come soon.

**Comment by antonkulaga** [comment]
@rkimoakbioinformatics if you plan to update the GUI anyways, maybe we can have a discussion? So far we tried not to bother you with GUI stuff as majors blockers where regular bugs and bugs in dbsnp/clinvar.

**Comment by rkimoakbioinformatics** [comment]
@antonkulaga Discussion would be good. Not right now, but maybe sometime next week?

**Comment by antonkulaga** [comment]
@rkimoakbioinformatics yes, next week will be good. We also noticed that you have an organizational sponshorship option for oakvar github repository, it will also be interesting to discuss it as well

**Comment by rkimoakbioinformatics** [comment]
@antonkulaga Sounds good and I have sent you an email. 

I have just released oakvar 2.5.13. It has significant improvement in the time for launching `ov gui`. At first, `ov gui` can take a bit of time, but afterwards it should take less than a second.

**Comment by antonkulaga** [comment]
UI is much faster now, thank you!

**Comment by antonkulaga** [comment]
Sorry, but I have to reopen it. It looks like the loading time is large again and it does not seem to cache properly

**Comment by rkimoakbioinformatics** [comment]
@antonkulaga I see. I do not see the behavior. What is your oakvar version and how long is the loading time? Also, how many modules are installed in your system and how many job folders are under <oakvar root dir>/jobs/default?

**Comment by antonkulaga** [comment]
@rkimoakbioinformatics can you check http://agingkills.eu:8081/result/index.html?job_id=220912-142913
For me it loads forever

**Comment by rkimoakbioinformatics** [comment]
@antonkulaga Working on a fix now.

**Comment by rkimoakbioinformatics** [comment]
@antonkulaga Please try oakvar v2.5.52.

**Comment by rkimoakbioinformatics** [comment]
It's been a while since the new version with the new GUI has been released. I believe that the issue was fixed. Closing for now. Please let me know if it still exists.
