### ISSUE TITLE
feature request: autodetect option for reference genome

### ISSUE THREAD

**Issue by antonkulaga** [rkimoakbioinformatics/oakvar#18]
Right now users have to select the refernce genome themselves and sometimes they make mistakes. At the same time usually reference genome is mentioned in the VCF file itself, maybe on top of hg37/38 you can provide detect_from_file option for reference genome>

**Comment by rkimoakbioinformatics** [comment]
@antonkulaga Please check with the new release oakvar 2.5.39. For VCF files, vcf-converter 2.1.8 should be used. One change is that now you can use input files of different genome assemblies. The genome assembly of each VCF-format input file is examined. `-l` option as in `ov run -l hg19` will override any auto-detected genome assembly.

**Comment by antonkulaga** [comment]
I think it is already implemented
