### ISSUE TITLE
feature request: the tab with available reports should be displayed in annotators results

### ISSUE THREAD

**Issue by antonkulaga** [rkimoakbioinformatics/oakvar#20]
The interface to select the appropriate reporter is hard to find and very unintuitive for users who just want to analyze their own genome. My suggestion is to display all reports that can be generated in a separate panel in annotation results. I provide a picture how it can look like (I composed it from reporters from app store but of course the descriptions should look a bit different when users generate reports for themselves)
![reporters](https://user-images.githubusercontent.com/842436/183292966-3a91036f-c59d-4f74-80b0-da401bbedb0a.png)

**Comment by rkimoakbioinformatics** [comment]
@antonkulaga I have just released oakvar 2.5.34, which has new result viewer UI (job submission and web store pages are still the same). In the result viewer page, click `Reports` tab and you'll be able to create and download reports.

To use this new result viewer the best, widget modules should be updated. I have released such new versions of some widgets. `ov module update` will update all the modules for which updates are available.

**Comment by antonkulaga** [comment]
@rkimoakbioinformatics I updated but cannot see it. Or it is availible only for newly run jobs?

UPD: looks pip still has 2.5.32 as the last version. Need to wait when it updates

**Comment by rkimoakbioinformatics** [comment]
@antonkulaga Oh, it could have been my mistake. I published it again and just confirmed that the 2.5.34 version is up on pypi.

**Comment by antonkulaga** [comment]
@rkimoakbioinformatics I checked. It looks much better than previos one. However, the loading time is huge. Maybe there are ways to either make it faster or display some progress bar to give user expectations?

**Comment by rkimoakbioinformatics** [comment]
I see. How many variants were in your job? Are you testing with the result of a personal genome's variants such as yours?

**Comment by rkimoakbioinformatics** [comment]
@antonkulaga Found the reason, which was surfaced by removing the 100k variant-limit. I'll release a fix shortly.

**Comment by antonkulaga** [comment]
I think removing the limit was good. However, as computing statistics for the summary takes time maybe you can put progress bar only on statistics. Alternatively you can turn it into a button

**Comment by rkimoakbioinformatics** [comment]
Indeed. I am testing with a result file with 3M variants, and gene-level summary of them takes a long time. How often do you use such information as the number of coding variants per gene and the list of variant consequences and their occurrence per gene (for example, "missense(2), stop_gain(3)")? 

I am thinking of two fixes: 1) the variant, gene, etc tabs will be enabled independently as their data arrive. 2) The gene level summary can be activated or not with a button.

**Comment by antonkulaga** [comment]
I think it is already implemented
