### ISSUE TITLE
feature request: use of pagination instead of 100K variants limit

### ISSUE THREAD

**Issue by antonkulaga** [rkimoakbioinformatics/oakvar#21]
From my and my collegues experiments 100K variants limitation is the most hated feature of oakvar. Why not just implementing pagination instead? The pagination can either be simple or it can be split by genome coordinates for navigation

**Comment by rkimoakbioinformatics** [comment]
@antonkulaga I have released oakvar 2.5.25, which has the pagination feature. There are several widget modules which were updated as well with this release, so `ov store fetch` and `ov module update` are recommended. 

When you open the result viewer for a job, the Variant tab will have pagination controls in the footer of the variant table. The size of one page can be changed, you can jump to a page number, and navigate by one page with prev and next buttons.

The default page size can be configured in the user conf file, the location of which can be known with `ov config user`. Change `gui_result_pagesize` to the number of variants per page.

**Comment by antonkulaga** [comment]
Looks good to us
