### ISSUE TITLE
feature request: presets for annotators and reporters

### ISSUE THREAD

**Issue by antonkulaga** [rkimoakbioinformatics/oakvar#22]
From our experience users are often confused which annotators to choose. Maybe it is possible to have something like presets that users can select if they do not know the annotators they need.
For example, it can be Oncogenetics, Heredetial diseases, or personal reports. Selecting the preset will add annotators that belong to it, so advanced users will select the old way while less advanced will just select presets.

**Comment by rkimoakbioinformatics** [comment]
@antonkulaga I agree. I have some ideas, but real use case input would be even better. When I get to the redesign of the job submission page, it'll be a good time to discuss about it.

**Comment by antonkulaga** [comment]
I think it is not super-relevant now as we can just publish reporters with all dependencies instead of having separate entities called presets
