### ISSUE TITLE
No drop-down list in the filter tab

### ISSUE THREAD

**Issue by OlgaBorysova** [rkimoakbioinformatics/oakvar#25]
**Describe the bug**
Drop-down list in the filter tab doesn't appear.

**To Reproduce**
Go to filter tab -> variant properties -> query builder -> Choose "Clinvar"->Clinical significance ->one of -> than click to the drop down list and nothing happens .
![IMG_20220811_163441_529](https://user-images.githubusercontent.com/94704827/184162669-42c1c781-0763-40cd-903c-35fc53d74942.jpg)

**Desktop (please complete the following information):**
 - OS: Windows
 - OakVar Version v2.5.25
 - Browser (if used) chrome, opera

**Comment by rkimoakbioinformatics** [comment]
@OlgaBorysova Thanks. Most likely, all ClinVar annotation was empty, which would lead to the empty select option box you observed. I just published oakvar 2.5.26, which will show "no option is available" in such a case. Please check if your job has any non-empty ClinVar annotation and if the new oakvar version would work for you.

**Comment by antonkulaga** [comment]
For me the bug looks fixed. However, it is up to @OlgaBorysova to check on her side.
![Screenshot from 2022-08-12 16-13-44](https://user-images.githubusercontent.com/842436/184363402-aea97d9a-83b9-4891-ad5e-ef29be8d6397.png)

**Comment by rkimoakbioinformatics** [comment]
@OlgaBorysova by the way, regarding your clinvar module, does "ov util test -m clinvar" pass? If it doesn't pass, the module has a problem. The latest version is 2022.06.14.1.

**Comment by OlgaBorysova** [comment]
Everything is fine. I re-uploaded also my vcf file.
