### ISSUE TITLE
Pagenation not loading data

### ISSUE THREAD

**Issue by Alex-Karmazin** [rkimoakbioinformatics/oakvar#27]
When click on next in pagination loading screen appears but never finish loading. Also, it happens when rows per page changed.

**To Reproduce**
Load vcf file, add dbsnp anotator. Anotate, go to variants and click next button or change number of rows per page.

**Desktop (please complete the following information):**
 - OS: Windows 10

 - OakVar Version: 2.5.34
 - Browser chrome
 

[antku_small.zip](https://github.com/rkimoakbioinformatics/oakvar/files/9437059/antku_small.zip)

**Comment by rkimoakbioinformatics** [comment]
Got it. I'll take a look.

**Comment by rkimoakbioinformatics** [comment]
@Alex-Karmazin I have released a fix as oakvar v2.5.35. Please check this version. This has just one fix for this issue, and another version with more UI improvements (prev and next page buttons, etc) as well as better result loading itself is under way.

**Comment by Alex-Karmazin** [comment]
Thank you, it works.
