### ISSUE TITLE
Duplicating rows when us annotators

### ISSUE THREAD

**Issue by Alex-Karmazin** [rkimoakbioinformatics/oakvar#28]
**Describe the bug**
If add anotators you will have duplicate rows

**To Reproduce**
Load vcf file, add dbsnp annotator, go to variants and sort by rsid. There will be at list two rsid some of them will be duplicated. If using more annotators more duplicates will appear. But not all rows have duplicates.

**Screenshots (optional)**
![Снимок экрана 2022-08-27 043010](https://user-images.githubusercontent.com/95565703/187009028-e819b5a4-026a-4fd8-8669-833e89d24ece.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - OakVar Version: 2.5.34
 - Browser chrome

[antku_small.zip](https://github.com/rkimoakbioinformatics/oakvar/files/9437090/antku_small.zip)

**Comment by rkimoakbioinformatics** [comment]
Thanks. I'll take a look.

**Comment by rkimoakbioinformatics** [comment]
@Alex-Karmazin I tried to reproduce, but the bug did not appear. I did:
```
ov run antku_small.vcf -a dbsnp
ov run antku_small.vcf.sqlite -a litvar # this one uses dbsnp as a secondary input.
ov gui antku_small.vcf.sqlite
```
The screenshot is below.
![Screenshot_20220829_170612](https://user-images.githubusercontent.com/13386712/187154670-4a1bf76b-a617-4fb8-bf29-d2a0d5a93cbd.png)

Can you attach or paste the content of the .log file? It has more detailed information abou the job.

**Comment by Alex-Karmazin** [comment]
I record a video how to reproduce this bug. https://youtu.be/kBw_JIh5IFM

**Comment by rkimoakbioinformatics** [comment]
@Alex-Karmazin Thanks. I tested the same process but still got only 1 row for the same rsID as the one in the video. 

I noticed that the total number of rows in the variant level table was 1554 in your video. The correct number should be 384. It's a guess, but can you do `ov module update` to update all the modules, especially the vcf-converter (the latest is 2.1.8), and run `ov gui` again and run the job?

**Comment by Alex-Karmazin** [comment]
When I was recording this video I got latest version OakVar with modules updated. I got vcf-converter 2.1.8 version. Should I uninstall OakVar and then install it again? Because at the beginning there was opencravat and then I updated it to OakVar and updated it several times. I guess something could left as legacy code, and it causes such strange behavior.

**Comment by rkimoakbioinformatics** [comment]
I see. That can't hurt, but I would check a couple of things first: first, when you do 'ov config user', is the default mapper 'gencode'? If not, please change hg38 to gencode and install  the 'gencode' module. 

Secondly, do the following test pass? 
'''
ov util test -m dbsnp
ov util test -m gencode
'''

**Comment by Alex-Karmazin** [comment]
Command ov config user has such output:
"""
converter: converter
genemapper: hg38
aggregator: aggregator
gui_port: 8060
multicore_mapper_mode: true
last_assembly: hg38
default_assembly: hg38
conf_path: C:\Users\karma\.oakvar\oakvar.yml
"""

Tests are:
dbsnp: PASS
gencode: FAIL

**Comment by Alex-Karmazin** [comment]
I changed genemapper to gencode and install gencode module. But it still fails test.

**Comment by Alex-Karmazin** [comment]
After cleanup and total uninstall and new install, it disappears.

**Comment by rkimoakbioinformatics** [comment]
@Alex-Karmazin I see. Did you do `ov system setup --clean` only, or removed the `modules` folder as well?

**Comment by Alex-Karmazin** [comment]
I just remove folders in UserData folder and in ROOT folder on my
primary disk C: I read your message about --clean argument after that. I
did not touch the modules folder, and it was enough to fix the problem.


пн, 5 сент. 2022 г. в 00:07, Ryangguk Kim ***@***.***>:

**Comment by rkimoakbioinformatics** [comment]
@Alex-Karmazin Thanks. I am not sure why such folders existed, but I'll keep that in mind for the future.
