### ISSUE TITLE
After setup there is no module webapps

### ISSUE THREAD

**Issue by Alex-Karmazin** [rkimoakbioinformatics/oakvar#3]
After installation and executing command ov system setup, ov gui did not start web server. In log I found thet it could not find webapps folder. Creating manually this folder in modules fix this issue. But when I click "install system modules" button in oakvar web interface it show me other error in terminal.
"""
OakVar Server is served at 0.0.0.0:8080
(To quit: Press Ctrl-C or Ctrl-Break if run on a Terminal or Windows, or click "Cancel" and then "Quit" if run through OakVar app on Mac OS)
[2022:06:13 21:24:10] Starting to install vcfreporter:3.2.1...
Collecting pyvcf
  Using cached PyVCF-0.6.8.tar.gz (34 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in PyVCF setup command: use_2to3 is invalid.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
"""

Last errors in wcravat.log are:
"""
Traceback (most recent call last):
  File "/home/alex/micromamba/envs/opencravat-longevity/lib/python3.9/site-packages/oakvar/cli_gui.py", line 407, in server_done
    task.result()
  File "/home/alex/micromamba/envs/opencravat-longevity/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/home/alex/micromamba/envs/opencravat-longevity/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/home/alex/micromamba/envs/opencravat-longevity/lib/python3.9/site-packages/oakvar/cli_gui.py", line 428, in start
    self.setup_routes()
  File "/home/alex/micromamba/envs/opencravat-longevity/lib/python3.9/site-packages/oakvar/cli_gui.py", line 509, in setup_routes
    self.app.router.add_static("/webapps",
  File "/home/alex/micromamba/envs/opencravat-longevity/lib/python3.9/site-packages/aiohttp/web_urldispatcher.py", line 1124, in add_static
    resource = StaticResource(
  File "/home/alex/micromamba/envs/opencravat-longevity/lib/python3.9/site-packages/aiohttp/web_urldispatcher.py", line 559, in __init__
    raise ValueError(f"No directory exists at '{directory}'") from error
ValueError: No directory exists at '/home/alex/.oakvar/modules/webapps'
2022/06/13 21:19:46: Serving OakVar server at 0.0.0.0:8080
2022/06/13 21:19:46: No directory exists at '/home/alex/.oakvar/modules/webapps'
Traceback (most recent call last):
  File "/home/alex/micromamba/envs/opencravat-longevity/lib/python3.9/site-packages/aiohttp/web_urldispatcher.py", line 557, in __init__
    raise ValueError("Not a directory")
ValueError: Not a directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/alex/micromamba/envs/opencravat-longevity/lib/python3.9/site-packages/oakvar/cli_gui.py", line 407, in server_done
    task.result()
  File "/home/alex/micromamba/envs/opencravat-longevity/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/home/alex/micromamba/envs/opencravat-longevity/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/home/alex/micromamba/envs/opencravat-longevity/lib/python3.9/site-packages/oakvar/cli_gui.py", line 428, in start
    self.setup_routes()
  File "/home/alex/micromamba/envs/opencravat-longevity/lib/python3.9/site-packages/oakvar/cli_gui.py", line 509, in setup_routes
    self.app.router.add_static("/webapps",
  File "/home/alex/micromamba/envs/opencravat-longevity/lib/python3.9/site-packages/aiohttp/web_urldispatcher.py", line 1124, in add_static
    resource = StaticResource(
  File "/home/alex/micromamba/envs/opencravat-longevity/lib/python3.9/site-packages/aiohttp/web_urldispatcher.py", line 559, in __init__
    raise ValueError(f"No directory exists at '{directory}'") from error
ValueError: No directory exists at '/home/alex/.oakvar/modules/webapps'
2022/06/13 21:23:54: Serving OakVar server at 0.0.0.0:8080
2022/06/13 21:23:55: 127.0.0.1 [13/Jun/2022:18:23:55 +0000] "GET /submit/nocache/index.html HTTP/1.1" 200 262 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36"
2022/06/13 21:23:55: 127.0.0.1 [13/Jun/2022:18:23:55 +0000] "GET /submit/jquery-3.3.1.min.js HTTP/1.1" 200 251 "http://0.0.0.0:8080/submit/nocache/index.html" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36"
2022/06/13 21:23:55: 127.0.0.1 [13/Jun/2022:18:23:55 +0000] "GET /result/js/jquery-ui-1.12.1.custom/jquery-ui.css HTTP/1.1" 200 236 "http://0.0.0.0:8080/submit/nocache/index.html" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36"
2022/06/13 21:23:55: 127.0.0.1 [13/Jun/2022:18:23:55 +0000] "GET /result/js/jquery-ui-1.12.1.custom/jquery-ui.min.js HTTP/1.1" 200 252 "http://0.0.0.0:8080/submit/nocache/index.html" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36"
2022/06/13 21:23:55: 127.0.0.1 [13/Jun/2022:18:23:55 +0000] "GET /submit/nocache/websubmit.css HTTP/1.1" 200 261 "http://0.0.0.0:8080/submit/nocache/index.html" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36"
2022/06/13 21:23:55: 127.0.0.1 [13/Jun/2022:18:23:55 +0000] "GET /result/css/pqselect.min.css HTTP/1.1" 200 234 "http://0.0.0.0:8080/submit/nocache/index.html" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36"
2022/06/13 21:23:55: 127.0.0.1 [13/Jun/2022:18:23:55 +0000] "GET /store/nocache/webstore.css HTTP/1.1" 200 261 "http://0.0.0.0:8080/submit/nocache/index.html" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36"
2022/06/13 21:23:55: 127.0.0.1 [13/Jun/2022:18:23:55 +0000] "GET /submit/pqselect.dev.customforsubmit.js HTTP/1.1" 200 250 "http://0.0.0.0:8080/submit/nocache/index.html" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36"
2022/06/13 21:23:55: 127.0.0.1 [13/Jun/2022:18:23:55 +0000] "GET /submit/nocache/websubmit.js HTTP/1.1" 200 276 "http://0.0.0.0:8080/submit/nocache/index.html" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36"
2022/06/13 21:23:55: 127.0.0.1 [13/Jun/2022:18:23:55 +0000] "GET /store/nocache/webstore.js HTTP/1.1" 200 276 "http://0.0.0.0:8080/submit/nocache/index.html" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36"
2022/06/13 21:23:55: 127.0.0.1 [13/Jun/2022:18:23:55 +0000] "GET /submit/Chart.bundle.min.js HTTP/1.1" 200 252 "http://0.0.0.0:8080/submit/nocache/index.html" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36"
2022/06/13 21:23:55: 127.0.0.1 [13/Jun/2022:18:23:55 +0000] "GET /store/js/showdown-1.9.1.min.js HTTP/1.1" 200 251 "http://0.0.0.0:8080/submit/nocache/index.html" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36"
2022/06/13 21:23:55: 127.0.0.1 [13/Jun/2022:18:23:55 +0000] "GET /store/getstoreurl HTTP/1.1" 200 179 "http://0.0.0.0:8080/submit/nocache/index.html" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36"
2022/06/13 21:23:55: 127.0.0.1 [13/Jun/2022:18:23:55 +0000] "GET /result/images/question.png HTTP/1.1" 200 235 "http://0.0.0.0:8080/submit/nocache/index.html" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36"
2022/06/13 21:23:55: 127.0.0.1 [13/Jun/2022:18:23:55 +0000] "GET /submit/logo.png HTTP/1.1" 200 237 "http://0.0.0.0:8080/submit/nocache/index.html" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36"
2022/06/13 21:23:55: 127.0.0.1 [13/Jun/2022:18:23:55 +0000] "GET /result/images/mail.png HTTP/1.1" 200 235 "http://0.0.0.0:8080/submit/nocache/index.html" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36"
2022/06/13 21:23:55: 127.0.0.1 [13/Jun/2022:18:23:55 +0000] "GET /submit/nocache/broken_wheel.gif HTTP/1.1" 200 262 "http://0.0.0.0:8080/submit/nocache/index.html" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36"
2022/06/13 21:23:55: 127.0.0.1 [13/Jun/2022:18:23:55 +0000] "GET /submit/menu.png HTTP/1.1" 200 233 "http://0.0.0.0:8080/submit/nocache/index.html" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36"
2022/06/13 21:23:55: 127.0.0.1 [13/Jun/2022:18:23:55 +0000] "GET /submit/nointernet.png HTTP/1.1" 200 237 "http://0.0.0.0:8080/submit/nocache/index.html" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36"
2022/06/13 21:23:55: 127.0.0.1 [13/Jun/2022:18:23:55 +0000] "GET /store/images/left_arrow.png HTTP/1.1" 200 235 "http://0.0.0.0:8080/submit/nocache/index.html" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36"
2022/06/13 21:23:55: 127.0.0.1 [13/Jun/2022:18:23:55 +0000] "GET /store/images/x-lg.svg HTTP/1.1" 200 238 "http://0.0.0.0:8080/submit/nocache/index.html" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36"
2022/06/13 21:23:55: 127.0.0.1 [13/Jun/2022:18:23:55 +0000] "GET /store/images/right_arrow.png HTTP/1.1" 200 235 "http://0.0.0.0:8080/submit/nocache/index.html" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36"
2022/06/13 21:23:55: 127.0.0.1 [13/Jun/2022:18:23:55 +0000] "GET /result/images/back_arrow.png HTTP/1.1" 200 237 "http://0.0.0.0:8080/submit/nocache/index.html" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36"
2022/06/13 21:23:55: 127.0.0.1 [13/Jun/2022:18:23:55 +0000] "GET /result/fonts/sourcesanspro-bold-webfont.woff HTTP/1.1" 200 237 "http://0.0.0.0:8080/submit/nocache/websubmit.css" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36"
2022/06/13 21:23:55: 127.0.0.1 [13/Jun/2022:18:23:55 +0000] "GET /result/fonts/roboto-light-webfont.woff HTTP/1.1" 200 237 "http://0.0.0.0:8080/submit/nocache/websubmit.css" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36"
2022/06/13 21:23:55: 127.0.0.1 [13/Jun/2022:18:23:55 +0000] "GET /result/fonts/roboto-bold-webfont.woff HTTP/1.1" 200 237 "http://0.0.0.0:8080/submit/nocache/websubmit.css" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36"
2022/06/13 21:23:55: 127.0.0.1 [13/Jun/2022:18:23:55 +0000] "GET /result/fonts/roboto-medium-webfont.woff HTTP/1.1" 200 237 "http://0.0.0.0:8080/submit/nocache/websubmit.css" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36"
2022/06/13 21:23:55: 127.0.0.1 [13/Jun/2022:18:23:55 +0000] "GET /submit/servermode HTTP/1.1" 200 178 "http://0.0.0.0:8080/submit/nocache/index.html" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36"
2022/06/13 21:23:55: 127.0.0.1 [13/Jun/2022:18:23:55 +0000] "GET /submit/reports HTTP/1.1" 200 177 "http://0.0.0.0:8080/submit/nocache/index.html" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36"
2022/06/13 21:23:55: 127.0.0.1 [13/Jun/2022:18:23:55 +0000] "GET /store/getbasemodules HTTP/1.1" 200 532 "http://0.0.0.0:8080/submit/nocache/index.html" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36"
2022/06/13 21:23:55: 127.0.0.1 [13/Jun/2022:18:23:55 +0000] "GET /submit/getsystemconfinfo HTTP/1.1" 200 1182 "http://0.0.0.0:8080/submit/nocache/index.html" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36"
2022/06/13 21:23:55: 127.0.0.1 [13/Jun/2022:18:23:55 +0000] "GET /submit/lastassembly HTTP/1.1" 200 160 "http://0.0.0.0:8080/submit/nocache/index.html" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36"
2022/06/13 21:23:55: Exception with /submit/logo_transparent.png
2022/06/13 21:23:55: Not Found
Traceback (most recent call last):
  File "/home/alex/micromamba/envs/opencravat-longevity/lib/python3.9/site-packages/oakvar/cli_gui.py", line 347, in middleware
    response = await handler(request)
  File "/home/alex/micromamba/envs/opencravat-longevity/lib/python3.9/site-packages/aiohttp/web_urldispatcher.py", line 690, in _handle
    raise HTTPNotFound
aiohttp.web_exceptions.HTTPNotFound: Not Found
2022/06/13 21:23:55: 127.0.0.1 [13/Jun/2022:18:23:55 +0000] "GET /submit/logo_transparent.png HTTP/1.1" 500 209 "http://0.0.0.0:8080/submit/nocache/index.html" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36"
2022/06/13 21:23:55: 127.0.0.1 [13/Jun/2022:18:23:55 +0000] "GET /submit/packageversions HTTP/1.1" 200 213 "http://0.0.0.0:8080/submit/nocache/index.html" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36"
2022/06/13 21:23:55: 127.0.0.1 [13/Jun/2022:18:23:55 +0000] "GET /submit/nocache/index.html HTTP/1.1" 304 202 "http://0.0.0.0:8080/submit/nocache/index.html" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36"
2022/06/13 21:23:59: 127.0.0.1 [13/Jun/2022:18:23:55 +0000] "GET /store/remote HTTP/1.1" 200 430422 "http://0.0.0.0:8080/submit/nocache/index.html" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36"
2022/06/13 21:23:59: 127.0.0.1 [13/Jun/2022:18:23:59 +0000] "GET /issystemready HTTP/1.1" 200 198 "http://0.0.0.0:8080/submit/nocache/index.html" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36"
2022/06/13 21:23:59: 127.0.0.1 [13/Jun/2022:18:23:59 +0000] "GET /submit/jobs HTTP/1.1" 200 158 "http://0.0.0.0:8080/submit/nocache/index.html" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36"
2022/06/13 21:23:59: 127.0.0.1 [13/Jun/2022:18:23:59 +0000] "GET /store/local HTTP/1.1" 200 69779 "http://0.0.0.0:8080/submit/nocache/index.html" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36"
2022/06/13 21:23:59: 127.0.0.1 [13/Jun/2022:18:23:59 +0000] "GET /submit/getjobs?ids=%5B%5D HTTP/1.1" 200 158 "http://0.0.0.0:8080/submit/nocache/index.html" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36"
2022/06/13 21:23:59: 127.0.0.1 [13/Jun/2022:18:23:59 +0000] "GET /submit/annotators HTTP/1.1" 200 711 "http://0.0.0.0:8080/submit/nocache/index.html" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36"
2022/06/13 21:23:59: 127.0.0.1 [13/Jun/2022:18:23:59 +0000] "GET /store/updates HTTP/1.1" 200 189 "http://0.0.0.0:8080/submit/nocache/index.html" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36"
2022/06/13 21:23:59: 127.0.0.1 [13/Jun/2022:18:23:59 +0000] "GET /submit/help.png HTTP/1.1" 200 235 "http://0.0.0.0:8080/submit/nocache/index.html" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36"
2022/06/13 21:24:08: Exception with /store/queueinstall?module=vcfreporter
2022/06/13 21:24:08: 'tuple' object has no attribute 'items'
Traceback (most recent call last):
  File "/home/alex/micromamba/envs/opencravat-longevity/lib/python3.9/site-packages/oakvar/cli_gui.py", line 347, in middleware
    response = await handler(request)
  File "/home/alex/micromamba/envs/opencravat-longevity/lib/python3.9/site-packages/oakvar/webstore/webstore.py", line 256, in queue_install
    for dep_name, dep_version in deps.items():
AttributeError: 'tuple' object has no attribute 'items'
2022/06/13 21:24:08: 127.0.0.1 [13/Jun/2022:18:24:07 +0000] "GET /store/queueinstall?module=vcfreporter HTTP/1.1" 500 239 "http://0.0.0.0:8080/submit/nocache/index.html" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36"
"""

**Comment by Alex-Karmazin** [comment]
I use Ubuntu 20.04.3 LTS 64 bit

**Comment by rkimoakbioinformatics** [comment]
@Alex-Karmazin Thanks. I'll look into it.

**Comment by rkimoakbioinformatics** [comment]
@Alex-Karmazin I have just published OakVar v2.4.8. Can you try this version?

**Comment by Alex-Karmazin** [comment]
Reinstaled v2.4.8 but still geting errors.
"""
The following modules will be installed:
- vcfreporter==3.2.1
Installing vcfreporter...
[2022:06:14 20:59:42] Starting to install vcfreporter:3.2.1...
Following PyPI dependencies should be met before installing vcfreporter.
- pyvcf
Installing required PyPI packages...
Collecting pyvcf
  Using cached PyVCF-0.6.8.tar.gz (34 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in PyVCF setup command: use_2to3 is invalid.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Following PyPI dependencies could not be installed.
- pyvcf
Skipping installation of vcfreporter==3.2.1 due to unmet requirement for PyPI packages
Done setting up the system
"""

**Comment by rkimoakbioinformatics** [comment]
@Alex-Karmazin Ah, that is the PyVCF problem which people have been experiencing since a while ago. It should be ported Python 3 somehow eventually by somebody. Until then, here is a solution. Before running ``ov system setup``,

```
>pip install "setuptools<58" --upgrade
>pip uninstall pyvcf
>pip install pyvcf
>pip install setuptools --upgrade
```

This will temporarily downgrade ``setuptools`` so that Python 2-based PyVCF is installed and then bring it back to the latest version.

After this, ``ov system setup`` will work normally.

**Comment by Alex-Karmazin** [comment]
Thank you it fixed problem.
