### ISSUE TITLE
[Feature] there should be separate Log for reporters as well as some way to display progress

### ISSUE THREAD

**Issue by antonkulaga** [rkimoakbioinformatics/oakvar#36]
Our CombinedLongevityReporter ( https://github.com/dna-seq/oakvar-longevity ) runs 30-60 minutes and it is frustrating experience for the user when (s)he cannot see the progress and log of the report. It would be nice to be able to see reports execution in a similar way to job ones.

**Comment by rkimoakbioinformatics** [comment]
Indeed. It was actually in the future items. I'll start discussion accordingly.

**Comment by antonkulaga** [comment]
As we refactored reporter with postagregators we do not need this feature anymore
