### ISSUE TITLE
submission does not clean up [BUG]

### ISSUE THREAD

**Issue by antonkulaga** [rkimoakbioinformatics/oakvar#38]
When I submit a genome and then want to submit a new one the old one does not disappear and Clear button does not help (at least in the latest Chrome)
![Screenshot from 2022-12-10 02-12-18](https://user-images.githubusercontent.com/842436/206814988-e94aee19-b65b-4705-8895-3f517a7a61c5.png)
on a screenshot you see that Olga genome is still there after switching tabs and trying clear button

**Comment by rkimoakbioinformatics** [comment]
Thanks. Please check v2.7.12 for a fix.
