### ISSUE TITLE
ov system setup can be blocked by email not coming

### ISSUE THREAD

**Issue by antonkulaga** [rkimoakbioinformatics/oakvar#4]
I am trying to update to the latest version.
It forces me to run:
```bash
ov system setup
```
That on its own asks to wait for a verification email. But the email never comes.
Maybe you can make it optional (if the user wants to activate the store he has to do it, but otherwise it should work out of the box) ?

**Comment by rkimoakbioinformatics** [comment]
oh, let me check the server.

**Comment by rkimoakbioinformatics** [comment]
it seems that the verification has a problem with gmail. a fix under way.

**Comment by rkimoakbioinformatics** [comment]
still fixing, but I manually verified your email. please try `ov system setup --clean`. It may ask you to enter the email and password for your account. Enter the same information and you'll be logged in without doing account creation and verification again.

**Comment by rkimoakbioinformatics** [comment]
@antonkulaga The server has been fixed.
