### ISSUE TITLE
please change the icon for manually entering variants [Feature]

### ISSUE THREAD

**Issue by antonkulaga** [rkimoakbioinformatics/oakvar#40]
So far the button to manually add variants is often confused with upload button, and honestly fits more for upload that current upload icon. Consider visual changes to avoid users confusion
![image](https://user-images.githubusercontent.com/842436/206817219-261f929f-f1d6-474e-bfab-647c72586355.png)

**Comment by rkimoakbioinformatics** [comment]
Thanks. Please check v2.7.12 for the change.
