### ISSUE TITLE
several users with empty login names are possible [BUG]

### ISSUE THREAD

**Issue by antonkulaga** [rkimoakbioinformatics/oakvar#41]
![Screenshot from 2022-12-25 20-18-49](https://user-images.githubusercontent.com/842436/209478438-27fdba32-fe62-4c68-a906-64fe5c5730d5.png)
You can notice several users with empty logins. I do not think such registration should be allowed

**Comment by rkimoakbioinformatics** [comment]
Thanks for the report. I'll check.

**Comment by rkimoakbioinformatics** [comment]
@antonkulaga I have published ov 2.7.24. It has "remove user" functionality on the System tab. Probably the empty users are artifacts from previous versions of ov and should not happen with the latest version. Please delete them with the "remove user" button as you hover over those empty users' rows. Then, let me know if empty users appear again in the future.

**Comment by antonkulaga** [comment]
So far did  not have such issue, I will close
