### ISSUE TITLE
[BUG] problems with gene filters

### ISSUE THREAD

**Issue by antonkulaga** [rkimoakbioinformatics/oakvar#45]
For some reasons genes that are easy to find by entrez id are not found with regular gene filtering interface.
![image](https://user-images.githubusercontent.com/842436/230386983-e18a79da-8b75-4a60-a459-b16d3e1f98e6.png)

**Comment by rkimoakbioinformatics** [comment]
I'll take a look.

**Comment by rkimoakbioinformatics** [comment]
OakVar v2.9.0 has been released and it should have the fix for the issue. Please check.
