### ISSUE TITLE
[BUG] dependent to a reporter modules get replaced by other modules if you choose more than one reporter

### ISSUE THREAD

**Issue by marfantyk** [rkimoakbioinformatics/oakvar#46]
In GUI, if you choose more than one reporter, dependent modules of the first chosen reporter will be replace (not summarized, as would be expected) by next chosen reporter. So not all required modules for both reporters will be chosen automatically

**Comment by rkimoakbioinformatics** [comment]
Thanks. I'll check it out.

**Comment by rkimoakbioinformatics** [comment]
ov 2.9.5 has been released with a fix for the issue.
