### ISSUE TITLE
[Feature] one button for applying filters

### ISSUE THREAD

**Issue by marfantyk** [rkimoakbioinformatics/oakvar#47]
I suggest to create just one button for both refreshing and loading filtered variants in all the sections of the results, as for now you have to first click "refresh" and then click "load" button. It might be confusing for users (at least it was for me when I tried to filter variants myself for the first time)

**Comment by rkimoakbioinformatics** [comment]
To load filtered data, pressing just "load" button will do. "Refresh" button is to quickly know how many variants will be retrieved with the filter without actually loading them - just counting. 

That said, maybe "refresh" is confusing?

I'll think about UI change.

**Comment by marfantyk** [comment]
Yes, might be both buttons are confusing. I would expect something like "apply" for my filter to be applied and maybe change the place of the button. Here is my suggestion that might be helpful
![image](https://user-images.githubusercontent.com/105512485/231565026-b7a397da-017c-432c-9ed4-f249e16ebffd.png)

**Comment by rkimoakbioinformatics** [comment]
Thanks for the suggestion. It looks good. ov 2.9.5 has the UI change.
