### ISSUE TITLE
[Feature] Small changes of GUI for uploading file and annotation button

### ISSUE THREAD

**Issue by marfantyk** [rkimoakbioinformatics/oakvar#48]
It has been a bit confusing for some users to understand whether annotation started or not after this screen:
![image](https://github.com/rkimoakbioinformatics/oakvar/assets/105512485/6a1b447e-74ce-4f98-ba8e-4bbacc54b8a3)

I may suggest to add some animation that it went to the "Results" section after VCF file was uploaded. Or maybe add a pop-up window with the message that vcf file was successfully uploaded,  annotation started, and you can find it in the "Results" section with a button for a user to confirm it, like "Okay" or "Got it"

**Comment by rkimoakbioinformatics** [comment]
Good suggestion. I'll reflect it in the next release.

**Comment by rkimoakbioinformatics** [comment]
ov v2.9.18 has been released with such a popup. Let me know if it clears up the confusion?

**Comment by marfantyk** [comment]
For me it looks just fine, thanks a lot! I will let you know if some users are still confused. For now will close the issue.
