### ISSUE TITLE
[BUG] Accessing GUI via 0.0.0.0 on WSL2

### ISSUE THREAD

**Issue by sinmojito** [rkimoakbioinformatics/oakvar#50]
When attempting to access the GUI on WSL2 (Ubuntu distro) - the browser throws the error 'Unable to connect. Firefox can’t establish a connection to the server at 0.0.0.0:8080.' According to [Networking considerations for WSL](https://learn.microsoft.com/en-us/windows/wsl/networking), when building a networking app in a Linux distribution on WSL, it can be accessed from a Windows browser using localhost, which is why I can access the application when manually changing the URL to http://localhost:8080. I wanted to ask if this behaviour is intended or if there's a configuration that should be adjusted for WSL. Also, I would appreciate confirmation on whether this would be different on native Linux, where 0.0.0.0 might work directly(which is what oakvar is mainly intended for I reckon).

To reproduce - 

Following the tutorial up to 'ov gui exampleinput.sqlite' step on a WSL2 enabled machine should produce this error. 

**Desktop**
 - OS: [e.g. Windows 11 with WSL2 Ubuntu distribution]
 - OakVar Version v2.9.34
 - Browser - Firefox and Microsoft Edge

Best, 
Mohit

**Comment by rkimoakbioinformatics** [comment]
Hi Mohit, 

Thanks. I don't have access to WSL2 at this moment. Can you let me know what you get in WSL2 with the following?
```python
import platform
print(platform.platform())
print(platform.system())
```

**Comment by rkimoakbioinformatics** [comment]
On Windows (no WSL), Mac, and Linux, 0.0.0.0 works.

**Comment by sinmojito** [comment]
The above command prints 'Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.31' - I tested the small fix in the util.py and it works on my WSL2 machine now. 

tested by changing util.py line 32 from 
 
```python
`if "Microsoft" in pl:
```
 to 
```python
if "Microsoft" in pl or "microsoft" in pl:
```

on my WSL2 device with a fresh oakvar install and following the tutorial.

Best,
Mohit

**Comment by sinmojito** [comment]
line 33*

**Comment by rkimoakbioinformatics** [comment]
Ah, indeed. Windows was using localhost as well. Since you found the solution, would you like to contribute to this repo with your fix? To do so, please follow the instruction at https://docs.github.com/en/get-started/quickstart/contributing-to-projects.

**Comment by sinmojito** [comment]
Yes I will do so! Thank you!
