### ISSUE TITLE
[BUG] `get_wgs_reader` method sometimes returns lowercase bases.

### ISSUE THREAD

**Issue by sinmojito** [rkimoakbioinformatics/oakvar#55]
I had noticed this issue before, but didn't think much of it. Today when I was trying to retrieve left and right contextual bases to construct SPDI notation, it had an impact. While a simple `base_at_pos = self._wgs_reader.get_bases(self.chrom, right_pos).upper()` helped on my end, perhaps worth looking into incase it causes further issues?

 - OS: WSL2 via Windows 11
 - OakVar Version [e.g. v2.9.36]
 
Run the following code to reproduce the error:

```
import oakvar as ov
wgs_reader = ov.get_wgs_reader(assembly="hg38")
bases = wgs_reader.get_bases("chr1", 55514277, 55514288)
print(bases)

**Comment by rkimoakbioinformatics** [comment]
Released a new version which can accept `get_bases(..., to_upper=True)`, which will convert bases to upper letters before returning.

**Comment by sinmojito** [comment]
Thank you. I will test the update once I get home from uni and will close the issue then.

**Comment by sinmojito** [comment]
Works as intended.
