### ISSUE TITLE
[BUG] Modules root directory does not exist.

### ISSUE THREAD

**Issue by vivekruhelaIIITD** [rkimoakbioinformatics/oakvar#58]
**Describe the bug**
I have just started using OakVar for variant annotation. I have successfully install the Oakvar using the instructions provided. Now,  in the first step, I am trying to install Clinvar database using the following command:

`ov module install clinvar`

Here I am getting the following error:

`modules root directory does not exist.`
`Following modules were not installed due to problems:`
`- clinvar`

**To Reproduce**
I gave the following command:
`ov module install clinvar`

**Expected behavior (optional)**
The command should run without any error.

**Screenshots (optional)**
![image](https://github.com/user-attachments/assets/2d65c1ca-3652-415b-a8ab-0b3a45212fcb)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - OakVar Version 2.11.4

**Comment by rkimoakbioinformatics** [comment]
Hi, thanks for the bug report. I'll take a look.

**Comment by rkimoakbioinformatics** [comment]
@vivekruhelaIIITD `modules root directory does not exist` means that the folder where OakVar modules should be stored does not exist. Check the following may give a clue.

* Run `ov system check` command: is there any error message?
* Have you run `ov system setup`?
* Did you use an external disk as the location for modules? If so, has the external disk been detached?

**Comment by vivekruhelaIIITD** [comment]
Thanks for responding. I checked the `ov compatibility` using `ov system check`, I got an error. Then I ran `ov system setup` which fixed it. Now I am able to run `ov module install clinvar`. I have attached the screenshot for your reference.

![image](https://github.com/user-attachments/assets/e1deb31e-4440-4d9b-b41f-3c75ef50473d)


Thanks.
