### ISSUE TITLE
minor bug with non-standard home folders

### ISSUE THREAD

**Issue by antonkulaga** [rkimoakbioinformatics/oakvar#9]
On one of the machines where I tried to deploy oakvar it was trying to write /home/antonkulaga instead of real user directory that was parked in another place ( /data/users/antonkulaga ). 
I found a workaround (just made a simlink), so things work for me (no need to rush fixing it).

**Comment by rkimoakbioinformatics** [comment]
@antonkulaga I have just published oakvar v2.5.6, which can handle your use case, which is explained at https://rkimoakbioinformatics.github.io/oakvar/install/ (see near the bottom of the page). It can be done by setting an environment variable `OV_ROOT_DIR` (as in `export OV_ROOT_DIR=/data/users/antonkulaga`) before running `ov system setup`.

**Comment by rkimoakbioinformatics** [comment]
Closing for now. Let me know if this issue still exists.

**Comment by antonkulaga** [comment]
export OV_ROOT_DIR
does not work with latest oakvar

**Comment by rkimoakbioinformatics** [comment]
Just released ov 2.8.20 which should work with OV_ROOT_DIR.
